spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/mariadb
        driverClassName: org.mariadb.jdbc.Driver
        username: root
        password: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
#auth:
#  jwtExpirationMs: 600000
#  jwtSecret: JWTSuperSecretKey